org: akaviles024
app: node-lambda-3
service: node-lambda-3
frameworkVersion: "3"

provider:
  name: aws
  runtime: nodejs18.x
  apiGateway:
    restApiId: ${cf:shared-gateway-dev.apiGatewayRestApiId}
    restApiRootResourceId: ${cf:node-lambda-1-dev.ApiGatewayResourceProducts}

functions:
  categories:
    handler: index.handler
    events:
      - http:
          path: categories
          method: get
